<%@ page import="java.util.Date" %>
<%@include file="/WEB-INF/ui/views/includes/default.jsp" %>
<% response.setContentType("text/javascript"); %>
//
// autogenerated on <%=new Date()%>
//
<%@include file="/WEB-INF/ui/views/api/libraries/js/core.js" %>

cs.api.v2 = {};
cs.api.v2.__internal = {};

cs.api.v2.__internal.executeMethod = function(apiMethod, executionParameters, callback){
    cs.api.__internal.ajax(apiMethod, executionParameters, null, callback);
};


<c:set var="js_namespace" value="cs.api.v2"/>
//
//
// V2 API REGISTRATIONS.
//
//
(function(){
<c:forEach var="apiService" varStatus="true" items="${apiServices}">
    //
    // ${apiService.serviceName} service methods.
    //
    ${js_namespace}.${apiService.serviceName} = new cs.api.base.APIService("${apiService.serviceName}", "v2");
    <c:forEach var="apiMethod" items="${apiService.methods}">
        var ___${apiService.serviceName}_${apiMethod.methodName} = ${js_namespace}.${apiService.serviceName}.registerAPIMethod("${apiMethod.methodName}", "${apiMethod.methodEndPoint}.json");
        <c:set var="paramSize" value="${fn:length(apiMethod.parameters)}"/>
        <c:choose>
            <c:when test="${paramSize>0}">
                <c:forEach var="apiParameter" items="${apiMethod.parameters}">___${apiService.serviceName}_${apiMethod.methodName}.registerAPIParameter("${apiParameter.paramName}", "${apiParameter.paramType}", ${apiParameter.required}, "${apiParameter.defaultValue}");
                </c:forEach>
            </c:when>
        </c:choose>
    </c:forEach>
</c:forEach>
})();

