tig:drop-stored-procedure("GetBinaryDataForFile"),
tig:drop-stored-procedure("CheckForPedigreeExistsForPortal"),
tig:drop-stored-procedure("CheckForSubscriberForPortal"),
tig:drop-stored-procedure("GetPedigreeIDFromPE"),
tig:drop-stored-procedure("allPedigrees"),
tig:drop-stored-procedure("getRepackagedInfo"),
tig:drop-stored-procedure("getPedigreeDocs_Invoice"),
tig:drop-stored-procedure("getPedigreeDocs_InvoiceAndNDC"),
tig:drop-stored-procedure("TPCustomization")