tig:drop-stored-procedure("getReportCubes"),
tig:drop-stored-procedure("getReportOuputFields"),
tig:drop-stored-procedure("getReportFilters"),
tig:drop-stored-procedure("getFilterFiledsMapping"),
tig:drop-stored-procedure("getOutputFieldsMapping"),
tig:drop-stored-procedure("getTradingPartnerList"),
tig:drop-stored-procedure("getreportStatus"),