/*
 * Copyright (c) Sourcen Inc. 2004-2012
 * All rights reserved.
 */

package com.sourcen.core;

/**
 * Any exception generated by Sourcen Framework should be a of type SourcenException or a subclass of SourcenException if we would
 * like to handle the exception within our code.
 * <p/>
 * These exceptions will allow us to throw & handle Checked Exceptions, and methods will have to specify "throws" clause
 * in their method declaration. We can either move the exception up the stackTrace, or handle it within our code.
 *
 * @author Navin Raj Kumar G.S.
 * @author $LastChangedBy: navinr $
 * @version $Revision: 2705 $, $Date:: 2012-05-29 10:26:39#$
 * @since 1.01
 */
public class SourcenException extends Exception {

    //
    // =================================================================================================================
    // == Class Fields ==
    // =================================================================================================================
    //

    /**
     * Serializable.
     */
    private static final long serialVersionUID = -6323924420053748365L;

    //
    // =================================================================================================================
    // == Constructors ==
    // =================================================================================================================
    //

    /**
     * Constructs a new SourcenRuntimeException with null as its detail message.
     */
    public SourcenException() {
    }

    /**
     * Constructs an SourcenException class with the specified detail message.
     *
     * @param message the detail message.
     */
    public SourcenException(final String message) {
        super(message);
    }

    /**
     * Constructs a new SourcenException with the specified detail message and cause.
     *
     * @param message the detail message.
     * @param cause   the cause of the exception
     */
    public SourcenException(final String message, final Throwable cause) {
        super(message, cause);
    }

    /**
     * Constructs a new SourcenException with the specified cause. The detailed message will be set to (cause==null ? null :
     * cause.toString());
     *
     * @param cause the cause of the exception
     */
    public SourcenException(final Throwable cause) {
        super(cause);
    }
}
