/*
 * Copyright (c) Sourcen Inc. 2004-2012
 * All rights reserved.
 */

package com.sourcen.core;

/**
 * Any runtime exceptions generated by Sourcen Framework should be a of type SourcenRuntimeException or a subclass of
 * SourcenRuntimeException which may not be necessary to be handled and mostly these exceptions occur to warn that something
 * may be going wrong, but can still proceed execution of the application.
 *
 * @author Navin Raj Kumar G.S.
 * @author $LastChangedBy: navinr $
 * @version $Revision: 2705 $, $Date:: 2012-05-29 10:26:39#$
 * @since 1.01
 */
public class SourcenRuntimeException extends RuntimeException {

    //
    // =================================================================================================================
    // == Class Fields ==
    // =================================================================================================================
    //

    /**
     * Serializable.
     */
    private static final long serialVersionUID = -7839453835986691582L;

    //
    // =================================================================================================================
    // == Constructors ==
    // =================================================================================================================
    //

    /**
     * Constructs a new SourcenRuntimeException with null as its detail message.
     */
    public SourcenRuntimeException() {
    }

    /**
     * Constructs an SourcenRuntimeException class with the specified detail message.
     *
     * @param message the detail message.
     */
    public SourcenRuntimeException(final String message) {
        super(message);
    }

    /**
     * Constructs a new SourcenRuntimeException with the specified detail message and cause.
     *
     * @param message the detail message.
     * @param cause   the cause of the exception
     */
    public SourcenRuntimeException(final String message, final Throwable cause) {
        super(message, cause);
    }

    /**
     * Constructs a new SourcenRuntimeException with the specified cause. The detailed message will be set to (cause==null ?
     * null : cause.toString());
     *
     * @param cause the cause of the exception
     */
    public SourcenRuntimeException(final Throwable cause) {
        super(cause);
    }
}
