var TREE_ITEMS = [
	['Grid Manager', null,
		['Locations', null,
			['Add', 'Location/Add.jsp'],
			['Edit', 'Location/Edit.html'],
			['Build Location', null,
				['Add', 'Location/AddGroup.html'],
				['Edit', 'Location/EditGroup.html'],
				['Location Filters', 'Location/GroupFilters.html'],
			],
		],
		['Products', null,
			['Add', 'Location/Add.jsp'],
			['Edit', 'Location/Edit.html'],
			['Build Location', null,
				['Add', 'Location/AddGroup.html'],
				['Edit', 'Location/EditGroup.html'],
				['Location Filters', 'Location/GroupFilters.html'],
			],
		],		
		['Readers', null,
			['Add', 'Readers/Add.html'],
			['Edit', 'Readers/Edit.html'],
		],
	],
	['Repositories', null,
		['Add', 'Repository/Add.html'],
		['Edit', 'Repository/Edit.html'],
		['Resources', null,
			['Users & Groups', 'Resources/UserGroups.html'],
			['DB Structures', 'Resources/DBStructures.html'],
			['DB Procedures', 'Resources/DBProcs.html'],
			['ONS', 'Resources/ONS.html'],
			['Replication', 'Resources/Replication.html'],
		],
		['Software Components', null,
			['Deploy New', 'Software/Add.html'],
			['View Existing', 'Software/Edit.html'],
		],
		['Subscriptions', null,
			['Add', 'Subscriptions/Add.html'],
			['Edit', 'Subscriptions/Edit.html'],
		],
	],
	['System Setup', null,
		['Events', null,
			['Add', 'Events/Add.html'],
			['Edit', 'Events/Edit.html'],
		],
		['Rules', null,
			['Add', 'Rules/Add.html'],
			['Edit', 'Rules/Edit.html'],
		],

		['Filters', null,
			['Add', 'Filters/Add.html'],
			['Edit', 'Filters/Edit.html'],
		],
		['Exceptions', null,
			['Add', 'Exceptions/Add.html'],
			['Edit', 'Exceptions/Edit.html'],
		],
		['Vocabularies', null,
					['System', 'Vocabulary/System.html'],
					['User', 'Vocabulary/User.html'],
		],
	],
	['KPI Dashboard', null,
		['Configure', 'Dashboard/Config.html'],
		['Run', 'Dashboard/Run.html'],
	],
	['EPC Tracking', null,
		['Run', 'Track/Track.html'],
	],
];