(: FOR PEDSHIP :)
tig:drop-stored-procedure("StringToNode"),
tig:drop-stored-procedure("UpDateLotQuantityforShippingNew"),
tig:drop-stored-procedure("UpdatePedigreeBankQuantityNew"),
tig:drop-stored-procedure("updatePedigreebankAfterShipmentNew"),
tig:drop-stored-procedure("GetPedigreeDetailsNew"),
tig:drop-stored-procedure("GetRPORInitialPedigreeDetails"),
tig:drop-stored-procedure("CreatedRepackagedElementNew"),
tig:drop-stored-procedure("CreateShippedPedigreeRepackedNew"),
tig:drop-stored-procedure("ShipGoodsNew"),
tig:drop-stored-procedure("GetRPID"),
tig:drop-stored-procedure("GetEmailId"),

(: FOR PEDRCV :)
tig:drop-stored-procedure("ndcExists"),
tig:drop-stored-procedure("UpDateTotalInventory"),
tig:drop-stored-procedure("CreateRepackageInstrDocForInitial"),
tig:drop-stored-procedure("InsertLot" ),
tig:drop-stored-procedure("insertLotinfoNodeNew"),
tig:drop-stored-procedure("replaceQty"),
tig:drop-stored-procedure("UpDatePedigreeBankDocForInitial"),
tig:drop-stored-procedure("UpDatePedigreeBankDocNew"), 
tig:drop-stored-procedure("createNewPedBankDocForInitial"),
tig:drop-stored-procedure("UpdatePedigreeBankForInitial"),
tig:drop-stored-procedure("CreateRepackageInstrDoc"),
tig:drop-stored-procedure("createNewPedBankDocNewschema"),
tig:drop-stored-procedure("CreateSignToReceivedPedigree"),
tig:drop-stored-procedure("CreateReceivedPedigreeForPedigrees1"),
tig:drop-stored-procedure("InsertAndChangePedigreeStatus1"),
tig:drop-stored-procedure("ReconcileGoods"),
tig:drop-stored-procedure("UpdateQuantity"),
tig:drop-stored-procedure("CloseCallNew")
